title: Mariel González
logo: assets/img/logo.jpg
description: Economista y financiera certificada en análisis de datos con sólida experiencia en extracción, limpieza y modelado de datos estratégicos. Comprometida con transformar datos en
soluciones prácticas que impulsan resultados medibles.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
